project/mysite/app2_allforms/urls.py
from django.urls import path
from django.views.generic import TemplateView

#from . import views
from app2_allforms.views import WhateverView
from app2_allforms.views import NeverlandView
from app2_allforms.views import IndexView
from app2_allforms.views import DetailViewA
from app2_allforms.views import DetailViewB
from app2_allforms.views import DetailViewC
from app2_allforms.views import EverythingCreate
from app2_allforms.views import EverythingDetail
from app2_allforms.views import EverythingUpdate
from app2_allforms.views import EverythingDelete



from . import views
from .models import ModelAllFormTypes

app_name = 'app2_allforms'
urlpatterns = [

    # as explained in:
    # https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-display/
    # there are a variety of views.

    # this uses the generic.TemplateView - no need to make a derived view class
    path('whomever/', TemplateView.as_view(template_name="app2_allforms/whomever.html")),

    # this uses a view derived from View 
    path('whatever/', WhateverView.as_view(), name='whatever'),

    # this uses a view derived from TemplateView
    path('neverland/', NeverlandView.as_view()),

    # for the index (list) we subclass ListView
    path('', views.IndexView.as_view()),

    # for the detail.. subclass DetailView and provide implementation of get_context_data
    # ex: /app2_allforms/A/5/
    path('A/<int:pk>/', DetailViewA.as_view(), name='detailA'),

    # The default implementation adds the object being displayed to the template, but you
    # can override it to send more:
    path('B/<int:pk>/', DetailViewB.as_view(), name='detailB'),

    # as described at
    # https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/
    # can generate forms class
    path('C/<int:pk>/', DetailViewC.as_view(), name='detailC'),


    path('everything/add/', EverythingCreate.as_view(), name='everything-add'),
    path('everything/<int:pk>/detail/', EverythingDetail.as_view(), name='everything-detail'),
    path('everything/<int:pk>/update/', EverythingUpdate.as_view(), name='everything-update'),
    path('everything/<int:pk>/delete/', EverythingDelete.as_view(), name='everything-delete'),
]

project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('app2_allforms/', include('app2_allforms.urls')),
    path('admin/', admin.site.urls),
]

project/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

project/mysite/app2_allforms/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create a database table with an attribute for each type of form
class ModelAllFormTypes(models.Model):
    your_name = models.CharField(max_length=200, null=True)
    a_date_time_field = models.DateTimeField('date published', null=True)

    def __str__(self):
        return self.your_name

    #def get_absolute_url(self):
    #    return reverse('app2_allforms.everything-detail', kwargs={'pk': self.pk})

    #def get_fields(self):
    #    return {
    #        #"your_name": self.your_name,
    #        "your_name": 'lala',
    #        "your_name2": 'lala2',
    #        #"a_date_time": a_date_time_field,
    #        }

project/mysite/app2_allforms/forms.py
from django import forms


class MyFormC(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

project/mysite/app2_allforms/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import HttpResponseRedirect
from django.http import HttpResponse

from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.urls import reverse_lazy

from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import ModelAllFormTypes
from .forms import MyFormC


class WhateverView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse('You have reached the Whatever page!')


class NeverlandView(TemplateView):

    template_name = 'app2_allforms/neverland.html'


class IndexView(ListView):

    model = ModelAllFormTypes
    template_name = 'app2_allforms/index.html'
    context_object_name = 'the_context_object'


class DetailViewA(DetailView):

    model = ModelAllFormTypes
    template_name = 'app2_allforms/detailA.html'
    context_object_name = 'the_context_object'


class DetailViewB(DetailView):

    model = ModelAllFormTypes
    template_name = 'app2_allforms/detailB.html'
    context_object_name = 'the_context_object'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        #context['book_list'] = Book.objects.all()
        context['message'] = "this is a message"
        return context


class DetailViewC(FormView):
    template_name = 'app2_allforms/detailC.html'
    form_class = MyFormC
    success_url = '/neverland/'
    context_object_name = 'the_context_object'

    def form_valid(self,form):
        return super().form_valid(form)


class EverythingDetail(DetailView):
    model = ModelAllFormTypes
    template_name = 'app2_allforms/everything_detail.html'
    fields = 'your_name'


class EverythingCreate(CreateView):
    model = ModelAllFormTypes
    template_name = 'app2_allforms/everything_add.html'
    fields = 'your_name'


class EverythingUpdate(UpdateView):
    model = ModelAllFormTypes
    template_name = 'app2_allforms/everything_update.html'
    fields = 'your_name'


class EverythingDelete(DeleteView):
    model = ModelAllFormTypes
    template_name = 'app2_allforms/everything_delete.html'
    success_url = reverse_lazy('app2_allforms')


#   def do_view_b(self, request):
#       # if this is a POST request we need to process the form data
#       if request.method == 'POST':
#           # create a form instance and populate it with data from the request:
#           form = AllTypesFormB(request.POST)
#           # check whether it's valid: 
# 
#           if form.is_valid():
#               # process the data in form.cleaned_data as required
#               # ...
#               # redirect to a new URL:
#               return HttpResponseRedirect('/thanks/')
#
#        # if a GET (or any other method) we'll create a blank form
#        else:
#            form = AllTypesFormB()
#
#        return render(request, 'name.html', {'form': form})

#def do_view_b(request, the_pk):
#    modelAllFormTypes = get_object_or_404(ModelAllFormTypes, pk=the_pk)

#    # if this is a POST request we need to process the form data
#    if request.method == 'POST':
#        # create a form instance and populate it with data from the request:
#       form = AllTypesFormB(request.POST)
#       # check whether it's valid:
#       #if form.is_valid():
#            # process the data in form.cleaned_data as required
#            # ...
#            # redirect to a new URL:
#            #return HttpResponseRedirect('/thanks/')

#    # if a GET (or any other method) we'll show the form data
#   else:
#        #data = {
#        #    'the_name': 'hello'}
#        #form = AllTypesFormB(data)

#        form = AllTypesFormB(modelAllFormTypes.get_fields())

#        #form = AllTypesFormB({'alpha':'the_alpha', 'beta':'the_beta'})
#        #form.your_name = "hello123"
#        #return HttpResponseRedirect('/thanks/')
#        #return HttpResponseRedirect('/app2_allforms/')
#        #return render(request, 'app2_allforms/B/3', {'form': form})
#        #return render(request, 'name.html', {'form': form})
#        return render(request=request, template_name='app2_allforms/detailB.html', context={'form': form})

project/mysite/app2_allforms/templates/app2_allforms/detailA.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>

<h1>This is Detail A</h1>

<h1>{{ object.your_name }}</h1>
<h1>{{ the_context_object.your_name }}</h1>
<p>your_name: {{the_context_object.your_name}}</p>
<p>a_date_time_field: {{ the_context_object.a_date_time_field}}</p>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/detailB.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>

<h1>This is Detail B</h1>

<form action="app2_allforms/B/3" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

<br>


<h1>{{ the_context_object.your_name }}</h1>
<p>your_name: {{the_context_object.your_name}}</p>
<p>a_date_time_field: {{ the_context_object.a_date_time_field}}</p>

</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/detailC.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>

<h1>This is Detail C</h1>

</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/everything-add.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Everything Add page</title>
</head>

<h1>This is Everything Add</h1>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/everything-delete.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Everything Delete page</title>
</head>

<h1>This is Everything Delete</h1>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/everything-detail.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Everything Detail page</title>
</head>

<h1>This is Everything Detail</h1>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/everything-update.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Everything Update page</title>
</head>

<h1>This is Everything Update</h1>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/get_name.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>

<h1>This is name 45</h1>

<form action="/get_name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>My test page</title>
</head>

<body>
    <p>This is index 7</p>

    {% if the_context_object %}
    <ul>
        {% for foo in the_context_object %}
        <li><a href="{% url 'app2_allforms:detailA' foo.id %}">{{ foo.your_name }}</a></li>
        <li><a href="{% url 'app2_allforms:detailB' foo.id %}">{{ foo.your_name }}</a></li>
        <li><a href="{% url 'app2_allforms:detailC' foo.id %}">{{ foo.your_name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No foos are available.</p>
    {% endif %}


</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/neverland.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Neverland Page</title>
</head>

<body>
    <p>This is the Neverland page</p>

</body>

</html>

project/mysite/app2_allforms/templates/app2_allforms/whomever.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Whomever Page</title>
</head>

<body>
    <p>This is the Whomever page</p>

</body>

</html>